# Generated by Django 6.0.2 on 2026-02-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='reels/'),
        ),
    ]
